
@hostName = https://api.themoviedb.org/3/
@apiKey = 29e9c21417a5cdd0f56b401142fdba10

### Now playing
GET {{hostName}}/movie/now_playing?api_key={{apiKey}}

### Get Popular
GET {{hostName}}/movie/popular?api_key={{apiKey}}&language=en-US&page=1

###
GET {{hostName}}/genre/movie/list?api_key={{apiKey}}&language=en-US
###
GET {{hostName}}/movie/502356?api_key={{apiKey}}&&append_to_response=releases

###
GET {{hostName}}/certification/movie/list?api_key={{apiKey}}

###
GET {{hostName}}/movie/502356/alternative_titles?api_key={{apiKey}}