import * as React from 'react';
import styles from './Episodes.module.scss';
import {
  FormControl,
  InputLabel,
  MenuItem,
  Select,
  SelectChangeEvent,
} from '@mui/material';
import { TMDBImage } from '../../setup/ultils/GetImageTmdb';
import ListLayout from '../ListLayout/ListLayout';
export interface IEpisodesProps {}

export default function Episodes(props: any) {
  const [age, setAge] = React.useState('');

  const handleChange = (event: SelectChangeEvent) => {
    setAge(event.target.value as string);
  };

  return (
    <section className={styles['episodes-container']}>
      <div className={styles['title-container']}>
        <span className={styles['title-episodes']}> Episodes</span>
        <span className={styles['dot']}>&#x2022;</span>
        <span className={styles['title-tv']}>Stranger Things</span>
      </div>
      <FormControl variant="standard" sx={{ m: 1, minWidth: 120 }}>
        <InputLabel id="demo-simple-select-label">Age</InputLabel>
        <Select
          labelId="demo-simple-select-label"
          id="demo-simple-select"
          value={age}
          label="Age"
          onChange={handleChange}
        >
          <MenuItem value={10}>Ten</MenuItem>
          <MenuItem value={20}>Twenty</MenuItem>
          <MenuItem value={30}>Thirty</MenuItem>
        </Select>
      </FormControl>
      <div className={styles['title-info']}>
        <p>Release year: 2016</p>
        <p className={styles['title-overview']}>
          Strange things are afoot in Hawkins, Indiana, where a young boy's
          sudden disappearance unearths a young girl with otherworldly powers.
        </p>
      </div>
      <div>
        <ListLayout>
          {episodes.episodes.map((episode, index) => {
            return <EpisodesCard {...episode} key={index} />;
          })}
        </ListLayout>
      </div>
    </section>
  );
}

const EpisodesCard = (props: any) => {
  return (
    <div className={styles['episodes-card-container']}>
      <img
        src={TMDBImage(props.still_path)}
        alt=""
        className={styles['episodes-image']}
      />
      <p className={styles['episodes-name']}>
        {props.episode_number}. {}
        {props.name}
      </p>
      <p className={styles['episodes-overview']}>{props.overview}</p>
    </div>
  );
};
const episodes = {
  _id: '5866a76592514102820000fd',
  air_date: '2017-10-27',
  episodes: [
    {
      air_date: '2017-10-27',
      episode_number: 1,
      id: 1250983,
      name: 'Chapter One: MADMAX',
      overview:
        'As the town preps for Halloween, a high-scoring rival shakes things up at the arcade, and a skeptical Hopper inspects a field of rotting pumpkins.',
      production_code: '',
      runtime: 48,
      season_number: 2,
      show_id: 66732,
      still_path: '/efz0MgPAxPw11PIeAJNgKKg3Paa.jpg',
      vote_average: 8.384,
      vote_count: 190,
      crew: [
        {
          job: 'Director',
          department: 'Directing',
          credit_id: '57b20164c3a36869e5000ba5',
          adult: false,
          gender: 2,
          id: 1179419,
          known_for_department: 'Writing',
          name: 'Matt Duffer',
          original_name: 'Matt Duffer',
          popularity: 3.732,
          profile_path: '/kXO5CnSxC0znMAICGxnPeuGP73U.jpg',
        },
        {
          job: 'Director',
          department: 'Directing',
          credit_id: '57b20174c3a3686a54000afa',
          adult: false,
          gender: 2,
          id: 1179422,
          known_for_department: 'Writing',
          name: 'Ross Duffer',
          original_name: 'Ross Duffer',
          popularity: 3.641,
          profile_path: '/kN1HdFViQkcJOQlNcvvFJIx9Uju.jpg',
        },
        {
          job: 'Writer',
          department: 'Writing',
          credit_id: '5789c497c3a36841e70009b9',
          adult: false,
          gender: 2,
          id: 1179422,
          known_for_department: 'Writing',
          name: 'Ross Duffer',
          original_name: 'Ross Duffer',
          popularity: 3.641,
          profile_path: '/kN1HdFViQkcJOQlNcvvFJIx9Uju.jpg',
        },
        {
          job: 'Writer',
          department: 'Writing',
          credit_id: '5789c46cc3a36841e700099e',
          adult: false,
          gender: 2,
          id: 1179419,
          known_for_department: 'Writing',
          name: 'Matt Duffer',
          original_name: 'Matt Duffer',
          popularity: 3.732,
          profile_path: '/kXO5CnSxC0znMAICGxnPeuGP73U.jpg',
        },
        {
          job: 'Unit Production Manager',
          department: 'Production',
          credit_id: '57eac2fd9251417e970003a3',
          adult: false,
          gender: 2,
          id: 1685635,
          known_for_department: 'Directing',
          name: 'Timothy J. Lonsdale',
          original_name: 'Timothy J. Lonsdale',
          popularity: 0.828,
          profile_path: null,
        },
        {
          job: 'First Assistant Director',
          department: 'Directing',
          credit_id: '59fcaa62925141138b0310b3',
          adult: false,
          gender: 0,
          id: 1228522,
          known_for_department: 'Directing',
          name: 'Richard Denault',
          original_name: 'Richard Denault',
          popularity: 0.6,
          profile_path: null,
        },
        {
          job: 'Writer',
          department: 'Writing',
          credit_id: '59fcaa00c3a3681adf02cdf1',
          adult: false,
          gender: 2,
          id: 1666689,
          known_for_department: 'Writing',
          name: 'Paul Dichter',
          original_name: 'Paul Dichter',
          popularity: 0.988,
          profile_path: null,
        },
        {
          job: 'Second Assistant Director',
          department: 'Directing',
          credit_id: '59fcaa83925141138b0310ed',
          adult: false,
          gender: 0,
          id: 1916849,
          known_for_department: 'Directing',
          name: 'Simeon Jones',
          original_name: 'Simeon Jones',
          popularity: 0.6,
          profile_path: null,
        },
        {
          job: 'Writer',
          department: 'Writing',
          credit_id: '59fcaa1d925141138b031070',
          adult: false,
          gender: 1,
          id: 1916848,
          known_for_department: 'Writing',
          name: 'Kate Trefry',
          original_name: 'Kate Trefry',
          popularity: 1.936,
          profile_path: '/RYoRQPYeGhSQP6y0X5x6LG8THM.jpg',
        },
        {
          job: 'Production Supervisor',
          department: 'Production',
          credit_id: '59fcaa9fc3a3681a8302d9e5',
          adult: false,
          gender: 1,
          id: 1887703,
          known_for_department: 'Production',
          name: 'Paula Kramer',
          original_name: 'Paula Kramer',
          popularity: 0.6,
          profile_path: null,
        },
        {
          job: 'Story Editor',
          department: 'Writing',
          credit_id: '59fca9bfc3a3681a8302d87b',
          adult: false,
          gender: 0,
          id: 1666688,
          known_for_department: 'Writing',
          name: 'Jessie Nickson-Lopez',
          original_name: 'Jessie Nickson-Lopez',
          popularity: 1.746,
          profile_path: null,
        },
        {
          job: 'Director of Photography',
          department: 'Camera',
          credit_id: '60a81c446ee3d70029419e54',
          adult: false,
          gender: 2,
          id: 1485876,
          known_for_department: 'Camera',
          name: 'Tim Ives',
          original_name: 'Tim Ives',
          popularity: 0.6,
          profile_path: '/cgQkPbS2akrEZlawCi5DN0AkPqs.jpg',
        },
      ],
      guest_stars: [
        {
          character: 'Cop #4',
          credit_id: '59fca76d92514113bf02ecaa',
          order: 501,
          adult: false,
          gender: 2,
          id: 168873,
          known_for_department: 'Acting',
          name: 'Gilbert Glenn Brown',
          original_name: 'Gilbert Glenn Brown',
          popularity: 2.79,
          profile_path: '/ht7bT1bu3MHh8mRIFXuGIWaX8KH.jpg',
        },
        {
          character: 'Tina',
          credit_id: '59fca794925141137f030762',
          order: 502,
          adult: false,
          gender: 1,
          id: 1642789,
          known_for_department: 'Acting',
          name: 'Madelyn Cline',
          original_name: 'Madelyn Cline',
          popularity: 55.543,
          profile_path: '/8NJlFxfa0sELKhmX494dasE9Ny5.jpg',
        },
        {
          character: 'Cop #1',
          credit_id: '59fca7d0c3a3681abb02f31c',
          order: 503,
          adult: false,
          gender: 2,
          id: 146020,
          known_for_department: 'Acting',
          name: 'Brian F. Durkin',
          original_name: 'Brian F. Durkin',
          popularity: 4.255,
          profile_path: '/e512f73OO7sx9e7WjIcqCKqLXqN.jpg',
        },
        {
          character: "Dr. Owens' Assistant",
          credit_id: '59fca82ac3a3681a6402d669',
          order: 504,
          adult: false,
          gender: 1,
          id: 1916840,
          known_for_department: 'Acting',
          name: 'Lauren Halperin',
          original_name: 'Lauren Halperin',
          popularity: 1.288,
          profile_path: '/qoBipKI23xiuYuCVMNuRCCREDRU.jpg',
        },
        {
          character: 'Cop #2',
          credit_id: '59fca851c3a3681a1b03188e',
          order: 505,
          adult: false,
          gender: 0,
          id: 1349052,
          known_for_department: 'Acting',
          name: 'Christopher Johnson',
          original_name: 'Christopher Johnson',
          popularity: 0.98,
          profile_path: null,
        },
        {
          character: 'Merril',
          credit_id: '59fca87d925141138b030e17',
          order: 506,
          adult: false,
          gender: 2,
          id: 187683,
          known_for_department: 'Acting',
          name: 'Fenton Lawless',
          original_name: 'Fenton Lawless',
          popularity: 1.109,
          profile_path: '/w43Cq1bDAPKTWfBuXr5kaJbr1P7.jpg',
        },
        {
          character: 'Mr. Holland',
          credit_id: '59fca8d292514113a602deaa',
          order: 507,
          adult: false,
          gender: 2,
          id: 1001687,
          known_for_department: 'Acting',
          name: 'Aaron Munoz',
          original_name: 'Aaron Munoz',
          popularity: 1.553,
          profile_path: '/szkmjJfm7pWk5aCX1RbLtsBrhzG.jpg',
        },
        {
          character: 'TV Reporter',
          credit_id: '59fca97692514113bb02ef89',
          order: 508,
          adult: false,
          gender: 2,
          id: 1916845,
          known_for_department: 'Acting',
          name: 'Ricardo Miguel Young',
          original_name: 'Ricardo Miguel Young',
          popularity: 0.6,
          profile_path: null,
        },
        {
          character: 'Axel',
          credit_id: '5a008e90925141471d06aadd',
          order: 509,
          adult: false,
          gender: 2,
          id: 1170659,
          known_for_department: 'Acting',
          name: 'James Landry Hébert',
          original_name: 'James Landry Hébert',
          popularity: 6.811,
          profile_path: '/1WC4pv2BWJGNqqoo3CnCelXmGEE.jpg',
        },
        {
          character: 'Vicki',
          credit_id: '5a2fe0fec3a3680b881798db',
          order: 510,
          adult: false,
          gender: 1,
          id: 1371456,
          known_for_department: 'Acting',
          name: 'Abigail Cowen',
          original_name: 'Abigail Cowen',
          popularity: 27.241,
          profile_path: '/ovv8pAF4eEKikyjXWxB56B98kJe.jpg',
        },
        {
          character: 'Pedestrian',
          credit_id: '5af87759c3a36845df001204',
          order: 511,
          adult: false,
          gender: 2,
          id: 1787406,
          known_for_department: 'Acting',
          name: 'Apollo GT',
          original_name: 'Apollo GT',
          popularity: 1.4,
          profile_path: '/fw6pIImSmsw6ywXuJzdhszULxkO.jpg',
        },
        {
          character: 'Donald Melvald',
          credit_id: '577a9f2492514174bb000db9',
          order: 523,
          adult: false,
          gender: 2,
          id: 1643635,
          known_for_department: 'Acting',
          name: 'Charles Lawlor',
          original_name: 'Charles Lawlor',
          popularity: 1.694,
          profile_path: '/yui3L3ugmNd8sYn9fJxGmzkTCxp.jpg',
        },
        {
          character: 'Eight / Kali',
          credit_id: '5bdba8630e0a26333a002cb2',
          order: 525,
          adult: false,
          gender: 1,
          id: 1616155,
          known_for_department: 'Acting',
          name: 'Linnea Berthelsen',
          original_name: 'Linnea Berthelsen',
          popularity: 5.265,
          profile_path: '/u2UOvGHI4IoVfJmtP1I8F68VR50.jpg',
        },
        {
          character: 'Nerdy Tech',
          credit_id: '59fca7f1c3a3681a8302d62d',
          order: 529,
          adult: false,
          gender: 0,
          id: 98191,
          known_for_department: 'Acting',
          name: 'Joe Davison',
          original_name: 'Joe Davison',
          popularity: 0.6,
          profile_path: null,
        },
        {
          character: 'Nicole',
          credit_id: '59fca70ec3a3681a6402d505',
          order: 534,
          adult: false,
          gender: 1,
          id: 1330503,
          known_for_department: 'Acting',
          name: 'Glennellen Anderson',
          original_name: 'Glennellen Anderson',
          popularity: 0.63,
          profile_path: null,
        },
        {
          character: 'Marsha Holland',
          credit_id: '59fca73bc3a3681acd02f597',
          order: 535,
          adult: false,
          gender: 1,
          id: 995451,
          known_for_department: 'Acting',
          name: 'Cynthia Barrett',
          original_name: 'Cynthia Barrett',
          popularity: 1.837,
          profile_path: '/tWd0Yr3uIkHxnJevJ5gFtsKp0LU.jpg',
        },
        {
          character: 'Principal Coleman',
          credit_id: '59fca957c3a3681a6402d7da',
          order: 540,
          adult: false,
          gender: 2,
          id: 114850,
          known_for_department: 'Acting',
          name: 'Tony Vaughn',
          original_name: 'Tony Vaughn',
          popularity: 3.503,
          profile_path: '/m99yAF6psRJSOslZkxPY8i7u7NR.jpg',
        },
        {
          character: 'Adams',
          credit_id: '59fca754925141137f030700',
          order: 560,
          adult: false,
          gender: 2,
          id: 1916834,
          known_for_department: 'Acting',
          name: 'Alan Boell',
          original_name: 'Alan Boell',
          popularity: 1.361,
          profile_path: '/vOgcUW3NqhI2IBvTaTBCJ8NX5pc.jpg',
        },
        {
          character: 'Keith',
          credit_id: '59fca77fc3a3681aa5032936',
          order: 579,
          adult: false,
          gender: 2,
          id: 979412,
          known_for_department: 'Acting',
          name: 'Matthew Cardarople',
          original_name: 'Matthew Cardarople',
          popularity: 6.458,
          profile_path: '/xhKO4iMPnwQS1GeDiY8vOyLFa8x.jpg',
        },
        {
          character: 'Florence',
          credit_id: '59fca93b92514113bb02ef2b',
          order: 600,
          adult: false,
          gender: 1,
          id: 1916844,
          known_for_department: 'Acting',
          name: 'Susan Shalhoub Larkin',
          original_name: 'Susan Shalhoub Larkin',
          popularity: 2.3,
          profile_path: '/pLAwhYAHjYyxMZrfCCgLBqLcmcU.jpg',
        },
        {
          character: 'Scott Clarke',
          credit_id: '5d2578ada698cf0010ab31cb',
          order: 605,
          adult: false,
          gender: 2,
          id: 1381393,
          known_for_department: 'Acting',
          name: 'Randy Havens',
          original_name: 'Randy Havens',
          popularity: 6.293,
          profile_path: '/7Lh5eGcXZUoPJcTWaUw369R706E.jpg',
        },
        {
          character: 'Flamethrower Soldier',
          credit_id: '5ec64d016c8492001f293ed6',
          order: 615,
          adult: false,
          gender: 2,
          id: 1396312,
          known_for_department: 'Acting',
          name: 'Dave MacDonald',
          original_name: 'Dave MacDonald',
          popularity: 0.84,
          profile_path: '/xqLpO30JWCyKkCQfuIBxIVSslpp.jpg',
        },
        {
          character: 'Calvin Powell',
          credit_id: '5d26171ea698cf52eba6bfae',
          order: 686,
          adult: false,
          gender: 2,
          id: 1281250,
          known_for_department: 'Acting',
          name: 'Rob Morgan',
          original_name: 'Rob Morgan',
          popularity: 9.099,
          profile_path: '/yIQd0L0kn1HyZGeEMkUREzMslP0.jpg',
        },
        {
          character: 'Phil Callahan',
          credit_id: '5d26185f37b3a96a3452a8a9',
          order: 693,
          adult: false,
          gender: 2,
          id: 1674830,
          known_for_department: 'Acting',
          name: 'John Reynolds',
          original_name: 'John Reynolds',
          popularity: 4.374,
          profile_path: '/1yzDTZqIeFQaI4i8eGC0TB1UfZg.jpg',
        },
        {
          character: 'Ted Wheeler',
          credit_id: '5d267e6774645700126c239a',
          order: 697,
          adult: false,
          gender: 2,
          id: 141762,
          known_for_department: 'Acting',
          name: 'Joe Chrest',
          original_name: 'Joe Chrest',
          popularity: 3.424,
          profile_path: '/ox45oYzfnI9mxDYNeP01ZTRWGXC.jpg',
        },
        {
          character: 'Carol Perkins',
          credit_id: '629dcd667d5db5086be91ed4',
          order: 708,
          adult: false,
          gender: 1,
          id: 1572103,
          known_for_department: 'Acting',
          name: 'Chelsea Talmadge',
          original_name: 'Chelsea Talmadge',
          popularity: 1.646,
          profile_path: '/cxH53B64fEjbI6u7uLTMjJFpAe2.jpg',
        },
        {
          character: 'Holly Wheeler',
          credit_id: '59fca91cc3a3681adf02ccbd',
          order: 747,
          adult: false,
          gender: 1,
          id: 1916843,
          known_for_department: 'Acting',
          name: 'Tinsley Price',
          original_name: 'Tinsley Price',
          popularity: 1.063,
          profile_path: '/y76Z7ewNyvPOvPudCNrHSFIuTth.jpg',
        },
      ],
    },
    {
      air_date: '2017-10-27',
      episode_number: 2,
      id: 1250984,
      name: 'Chapter Two: Trick or Treat, Freak',
      overview:
        "After Will sees something terrible on trick-or-treat night, Mike wonders whether Eleven's still out there. Nancy wrestles with the truth about Barb.",
      production_code: '',
      runtime: 56,
      season_number: 2,
      show_id: 66732,
      still_path: '/oGMZxF4yivOSCGZTMgiDD2Ye2Hi.jpg',
      vote_average: 8.0,
      vote_count: 127,
      crew: [
        {
          job: 'Director',
          department: 'Directing',
          credit_id: '57b20164c3a36869e5000ba5',
          adult: false,
          gender: 2,
          id: 1179419,
          known_for_department: 'Writing',
          name: 'Matt Duffer',
          original_name: 'Matt Duffer',
          popularity: 3.732,
          profile_path: '/kXO5CnSxC0znMAICGxnPeuGP73U.jpg',
        },
        {
          job: 'Director',
          department: 'Directing',
          credit_id: '57b20174c3a3686a54000afa',
          adult: false,
          gender: 2,
          id: 1179422,
          known_for_department: 'Writing',
          name: 'Ross Duffer',
          original_name: 'Ross Duffer',
          popularity: 3.641,
          profile_path: '/kN1HdFViQkcJOQlNcvvFJIx9Uju.jpg',
        },
        {
          job: 'Writer',
          department: 'Writing',
          credit_id: '5789c497c3a36841e70009b9',
          adult: false,
          gender: 2,
          id: 1179422,
          known_for_department: 'Writing',
          name: 'Ross Duffer',
          original_name: 'Ross Duffer',
          popularity: 3.641,
          profile_path: '/kN1HdFViQkcJOQlNcvvFJIx9Uju.jpg',
        },
        {
          job: 'Writer',
          department: 'Writing',
          credit_id: '5789c46cc3a36841e700099e',
          adult: false,
          gender: 2,
          id: 1179419,
          known_for_department: 'Writing',
          name: 'Matt Duffer',
          original_name: 'Matt Duffer',
          popularity: 3.732,
          profile_path: '/kXO5CnSxC0znMAICGxnPeuGP73U.jpg',
        },
        {
          job: 'Director of Photography',
          department: 'Camera',
          credit_id: '60a81c446ee3d70029419e54',
          adult: false,
          gender: 2,
          id: 1485876,
          known_for_department: 'Camera',
          name: 'Tim Ives',
          original_name: 'Tim Ives',
          popularity: 0.6,
          profile_path: '/cgQkPbS2akrEZlawCi5DN0AkPqs.jpg',
        },
      ],
      guest_stars: [
        {
          character: 'Erica Sinclair',
          credit_id: '5d268d58dc86470012a56065',
          order: 14,
          adult: false,
          gender: 1,
          id: 2029806,
          known_for_department: 'Acting',
          name: 'Priah Ferguson',
          original_name: 'Priah Ferguson',
          popularity: 7.9,
          profile_path: '/wkVKPGdtqNQxr7zlKPpBFY63Rbv.jpg',
        },
        {
          character: 'Government Agent #1',
          credit_id: '5b1f1288c3a36808a3013cad',
          order: 513,
          adult: false,
          gender: 1,
          id: 1001775,
          known_for_department: 'Acting',
          name: 'Tonya Bludsworth',
          original_name: 'Tonya Bludsworth',
          popularity: 1.301,
          profile_path: '/6z68gggGbrY1uidDU9tgk8TSS27.jpg',
        },
        {
          character: 'Government Agent #2',
          credit_id: '5b1f12a1c3a36808a600e345',
          order: 514,
          adult: false,
          gender: 2,
          id: 1223403,
          known_for_department: 'Acting',
          name: 'Jim E. Chandler',
          original_name: 'Jim E. Chandler',
          popularity: 1.244,
          profile_path: '/aqapPNP4axZI9roXrlfdwf0shgo.jpg',
        },
        {
          character: 'Eugene',
          credit_id: '5b1f12ad0e0a264faa01279d',
          order: 515,
          adult: false,
          gender: 2,
          id: 1391125,
          known_for_department: 'Acting',
          name: 'Al Mitchell',
          original_name: 'Al Mitchell',
          popularity: 2.846,
          profile_path: '/126oqauePaHdnMObEVb02ounBbo.jpg',
        },
        {
          character: 'Drunk Teen #1 (as Cody Land Pressley)',
          credit_id: '5b1f12ba0e0a264fbb011b7d',
          order: 516,
          adult: false,
          gender: 0,
          id: 2021938,
          known_for_department: 'Acting',
          name: 'Cody Pressley',
          original_name: 'Cody Pressley',
          popularity: 0.6,
          profile_path: null,
        },
        {
          character: 'Hawkins PD (uncredited)',
          credit_id: '5b1f12c7c3a368088f0114f8',
          order: 517,
          adult: false,
          gender: 2,
          id: 1635144,
          known_for_department: 'Acting',
          name: 'Trey McGriff',
          original_name: 'Trey McGriff',
          popularity: 0.97,
          profile_path: '/iuGh6AGdnfLdPEB93bQxnGiq48W.jpg',
        },
        {
          character: 'Playboy Bunny (uncredited)',
          credit_id: '5b1f12d30e0a264fad012f67',
          order: 518,
          adult: false,
          gender: 0,
          id: 2062528,
          known_for_department: 'Acting',
          name: 'Stephanie Mikel',
          original_name: 'Stephanie Mikel',
          popularity: 0.6,
          profile_path: null,
        },
        {
          character: 'Rift Soldier (uncredited)',
          credit_id: '5b1f12e20e0a264fb901239f',
          order: 519,
          adult: false,
          gender: 0,
          id: 1932326,
          known_for_department: 'Acting',
          name: 'Parker Allen',
          original_name: 'Parker Allen',
          popularity: 0.6,
          profile_path: null,
        },
        {
          character: 'Sweaty Teen Boy / Drunk Teen #2',
          credit_id: '5bc10dc40e0a266e640220ca',
          order: 522,
          adult: false,
          gender: 2,
          id: 1944274,
          known_for_department: 'Acting',
          name: 'Drew Scheid',
          original_name: 'Drew Scheid',
          popularity: 9.122,
          profile_path: '/ztj1zSSOLe5WtpvNVVIP1ir4xqa.jpg',
        },
        {
          character: 'Barbara “Barb” Holland',
          credit_id: '59f6602c925141428202220d',
          order: 553,
          adult: false,
          gender: 1,
          id: 1753911,
          known_for_department: 'Acting',
          name: 'Shannon Purser',
          original_name: 'Shannon Purser',
          popularity: 2.458,
          profile_path: '/zI5C3e0Rk5GjIdP7S4Dfde8R12N.jpg',
        },
        {
          character: 'Claudia Henderson',
          credit_id: '5d25787669d2801be0036fc0',
          order: 643,
          adult: false,
          gender: 1,
          id: 205808,
          known_for_department: 'Acting',
          name: 'Catherine Curtin',
          original_name: 'Catherine Curtin',
          popularity: 5.288,
          profile_path: '/giB5pkibdukMBHAE0yLGs1JsPOH.jpg',
        },
        {
          character: 'Calvin Powell',
          credit_id: '5d26171ea698cf52eba6bfae',
          order: 686,
          adult: false,
          gender: 2,
          id: 1281250,
          known_for_department: 'Acting',
          name: 'Rob Morgan',
          original_name: 'Rob Morgan',
          popularity: 9.099,
          profile_path: '/yIQd0L0kn1HyZGeEMkUREzMslP0.jpg',
        },
        {
          character: 'Sue Sinclair',
          credit_id: '5b1f12950e0a264f9b010eba',
          order: 690,
          adult: false,
          gender: 1,
          id: 1377994,
          known_for_department: 'Acting',
          name: 'Karen Ceesay',
          original_name: 'Karen Ceesay',
          popularity: 2.345,
          profile_path: '/j7EKFC2RZa0gBMcJJTRhhydONEX.jpg',
        },
        {
          character: 'Phil Callahan',
          credit_id: '5d26185f37b3a96a3452a8a9',
          order: 693,
          adult: false,
          gender: 2,
          id: 1674830,
          known_for_department: 'Acting',
          name: 'John Reynolds',
          original_name: 'John Reynolds',
          popularity: 4.374,
          profile_path: '/1yzDTZqIeFQaI4i8eGC0TB1UfZg.jpg',
        },
        {
          character: 'Ted Wheeler',
          credit_id: '5d267e6774645700126c239a',
          order: 697,
          adult: false,
          gender: 2,
          id: 141762,
          known_for_department: 'Acting',
          name: 'Joe Chrest',
          original_name: 'Joe Chrest',
          popularity: 3.424,
          profile_path: '/ox45oYzfnI9mxDYNeP01ZTRWGXC.jpg',
        },
        {
          character: 'Carol Perkins',
          credit_id: '629dcd667d5db5086be91ed4',
          order: 708,
          adult: false,
          gender: 1,
          id: 1572103,
          known_for_department: 'Acting',
          name: 'Chelsea Talmadge',
          original_name: 'Chelsea Talmadge',
          popularity: 1.646,
          profile_path: '/cxH53B64fEjbI6u7uLTMjJFpAe2.jpg',
        },
      ],
    },
    {
      air_date: '2017-10-27',
      episode_number: 3,
      id: 1250985,
      name: 'Chapter Three: The Pollywog',
      overview:
        'Dustin adopts a strange new pet, and Eleven grows increasingly impatient. A well-meaning Bob urges Will to stand up to his fears.',
      production_code: '',
      runtime: 51,
      season_number: 2,
      show_id: 66732,
      still_path: '/8Tc7f8Ab5LpcFpE88NUjcig9Ie1.jpg',
      vote_average: 8.1,
      vote_count: 118,
      crew: [
        {
          job: 'Director',
          department: 'Directing',
          credit_id: '57b201e6c3a368019a003110',
          adult: false,
          gender: 2,
          id: 17825,
          known_for_department: 'Production',
          name: 'Shawn Levy',
          original_name: 'Shawn Levy',
          popularity: 17.858,
          profile_path: '/b1ulkCHz8biG87LjLQQiMCebEZo.jpg',
        },
        {
          job: 'Writer',
          department: 'Writing',
          credit_id: '57b203009251411a45000bb8',
          adult: false,
          gender: 2,
          id: 1301304,
          known_for_department: 'Writing',
          name: 'Justin Doble',
          original_name: 'Justin Doble',
          popularity: 0.6,
          profile_path: '/7bTwDKXb8BsvI5b1b4UeKQhBCCN.jpg',
        },
        {
          job: 'Director of Photography',
          department: 'Camera',
          credit_id: '60a81c4dbbd0b0002b40b3f3',
          adult: false,
          gender: 2,
          id: 1580138,
          known_for_department: 'Camera',
          name: 'Tod Campbell',
          original_name: 'Tod Campbell',
          popularity: 2.193,
          profile_path: '/897Bl0aU94N0otv4Ab1gCr29yDV.jpg',
        },
      ],
      guest_stars: [
        {
          character: 'Vicki',
          credit_id: '5a2fe0fec3a3680b881798db',
          order: 510,
          adult: false,
          gender: 1,
          id: 1371456,
          known_for_department: 'Acting',
          name: 'Abigail Cowen',
          original_name: 'Abigail Cowen',
          popularity: 27.241,
          profile_path: '/ovv8pAF4eEKikyjXWxB56B98kJe.jpg',
        },
        {
          character: 'Sweaty Teen Boy / Drunk Teen #2',
          credit_id: '5bc10dc40e0a266e640220ca',
          order: 522,
          adult: false,
          gender: 2,
          id: 1944274,
          known_for_department: 'Acting',
          name: 'Drew Scheid',
          original_name: 'Drew Scheid',
          popularity: 9.122,
          profile_path: '/ztj1zSSOLe5WtpvNVVIP1ir4xqa.jpg',
        },
        {
          character: 'Marsha Holland',
          credit_id: '59fca73bc3a3681acd02f597',
          order: 535,
          adult: false,
          gender: 1,
          id: 995451,
          known_for_department: 'Acting',
          name: 'Cynthia Barrett',
          original_name: 'Cynthia Barrett',
          popularity: 1.837,
          profile_path: '/tWd0Yr3uIkHxnJevJ5gFtsKp0LU.jpg',
        },
        {
          character: 'Happy Homeowner',
          credit_id: '5d25838aa698cf59f5a7882d',
          order: 555,
          adult: false,
          gender: 1,
          id: 1493882,
          known_for_department: 'Acting',
          name: 'Lynne Ashe',
          original_name: 'Lynne Ashe',
          popularity: 1.413,
          profile_path: '/cUfEMdv3aQz2L17rnnSSmRpyhXC.jpg',
        },
        {
          character: 'Elderly Math Teacher',
          credit_id: '5d2583d637b3a90011530ef6',
          order: 556,
          adult: false,
          gender: 0,
          id: 1386350,
          known_for_department: 'Acting',
          name: 'Donna Wright',
          original_name: 'Donna Wright',
          popularity: 0.6,
          profile_path: null,
        },
        {
          character: 'Tommy H.',
          credit_id: '5d257ea9e24e3a00132bf3ff',
          order: 571,
          adult: false,
          gender: 2,
          id: 1694082,
          known_for_department: 'Acting',
          name: 'Chester Rushing',
          original_name: 'Chester Rushing',
          popularity: 2.522,
          profile_path: '/34YpCnyxCgxlq5PYJqiro7losWy.jpg',
        },
        {
          character: 'Florence',
          credit_id: '59fca93b92514113bb02ef2b',
          order: 600,
          adult: false,
          gender: 1,
          id: 1916844,
          known_for_department: 'Acting',
          name: 'Susan Shalhoub Larkin',
          original_name: 'Susan Shalhoub Larkin',
          popularity: 2.3,
          profile_path: '/pLAwhYAHjYyxMZrfCCgLBqLcmcU.jpg',
        },
        {
          character: 'Scott Clarke',
          credit_id: '5d2578ada698cf0010ab31cb',
          order: 605,
          adult: false,
          gender: 2,
          id: 1381393,
          known_for_department: 'Acting',
          name: 'Randy Havens',
          original_name: 'Randy Havens',
          popularity: 6.293,
          profile_path: '/7Lh5eGcXZUoPJcTWaUw369R706E.jpg',
        },
        {
          character: 'Claudia Henderson',
          credit_id: '5d25787669d2801be0036fc0',
          order: 643,
          adult: false,
          gender: 1,
          id: 205808,
          known_for_department: 'Acting',
          name: 'Catherine Curtin',
          original_name: 'Catherine Curtin',
          popularity: 5.288,
          profile_path: '/giB5pkibdukMBHAE0yLGs1JsPOH.jpg',
        },
        {
          character: 'Calvin Powell',
          credit_id: '5d26171ea698cf52eba6bfae',
          order: 686,
          adult: false,
          gender: 2,
          id: 1281250,
          known_for_department: 'Acting',
          name: 'Rob Morgan',
          original_name: 'Rob Morgan',
          popularity: 9.099,
          profile_path: '/yIQd0L0kn1HyZGeEMkUREzMslP0.jpg',
        },
        {
          character: 'Phil Callahan',
          credit_id: '5d26185f37b3a96a3452a8a9',
          order: 693,
          adult: false,
          gender: 2,
          id: 1674830,
          known_for_department: 'Acting',
          name: 'John Reynolds',
          original_name: 'John Reynolds',
          popularity: 4.374,
          profile_path: '/1yzDTZqIeFQaI4i8eGC0TB1UfZg.jpg',
        },
      ],
    },
    {
      air_date: '2017-10-27',
      episode_number: 4,
      id: 1250986,
      name: 'Chapter Four: Will the Wise',
      overview:
        'An ailing Will opens up to Joyce -- with disturbing results. While Hopper digs for the truth, Eleven unearths a surprising discovery.',
      production_code: '',
      runtime: 46,
      season_number: 2,
      show_id: 66732,
      still_path: '/wZ7ZDnftX9Y1O25I5tOaEKdK7FT.jpg',
      vote_average: 8.2,
      vote_count: 116,
      crew: [
        {
          job: 'Director',
          department: 'Directing',
          credit_id: '57b201e6c3a368019a003110',
          adult: false,
          gender: 2,
          id: 17825,
          known_for_department: 'Production',
          name: 'Shawn Levy',
          original_name: 'Shawn Levy',
          popularity: 17.858,
          profile_path: '/b1ulkCHz8biG87LjLQQiMCebEZo.jpg',
        },
        {
          job: 'Writer',
          department: 'Writing',
          credit_id: '59fcaa00c3a3681adf02cdf1',
          adult: false,
          gender: 2,
          id: 1666689,
          known_for_department: 'Writing',
          name: 'Paul Dichter',
          original_name: 'Paul Dichter',
          popularity: 0.988,
          profile_path: null,
        },
        {
          job: 'Director of Photography',
          department: 'Camera',
          credit_id: '60a81c4dbbd0b0002b40b3f3',
          adult: false,
          gender: 2,
          id: 1580138,
          known_for_department: 'Camera',
          name: 'Tod Campbell',
          original_name: 'Tod Campbell',
          popularity: 2.193,
          profile_path: '/897Bl0aU94N0otv4Ab1gCr29yDV.jpg',
        },
      ],
      guest_stars: [
        {
          character: 'Sweaty Teen Boy / Drunk Teen #2',
          credit_id: '5bc10dc40e0a266e640220ca',
          order: 522,
          adult: false,
          gender: 2,
          id: 1944274,
          known_for_department: 'Acting',
          name: 'Drew Scheid',
          original_name: 'Drew Scheid',
          popularity: 9.122,
          profile_path: '/ztj1zSSOLe5WtpvNVVIP1ir4xqa.jpg',
        },
        {
          character: 'Middle-Aged Man',
          credit_id: '5d25899a37b3a902ce52bfa4',
          order: 570,
          adult: false,
          gender: 2,
          id: 97446,
          known_for_department: 'Acting',
          name: 'James DuMont',
          original_name: 'James DuMont',
          popularity: 5.048,
          profile_path: '/8DLNFj3a4SJWdtw5daPBQm0qrOO.jpg',
        },
        {
          character: 'Tommy H.',
          credit_id: '5d257ea9e24e3a00132bf3ff',
          order: 571,
          adult: false,
          gender: 2,
          id: 1694082,
          known_for_department: 'Acting',
          name: 'Chester Rushing',
          original_name: 'Chester Rushing',
          popularity: 2.522,
          profile_path: '/34YpCnyxCgxlq5PYJqiro7losWy.jpg',
        },
        {
          character: 'Park Goer',
          credit_id: '5d2589eea698cf0fa7a85a9e',
          order: 572,
          adult: false,
          gender: 0,
          id: 2358416,
          known_for_department: 'Acting',
          name: 'Olivia De Paux',
          original_name: 'Olivia De Paux',
          popularity: 0.6,
          profile_path: null,
        },
        {
          character: 'Scott Clarke',
          credit_id: '5d2578ada698cf0010ab31cb',
          order: 605,
          adult: false,
          gender: 2,
          id: 1381393,
          known_for_department: 'Acting',
          name: 'Randy Havens',
          original_name: 'Randy Havens',
          popularity: 6.293,
          profile_path: '/7Lh5eGcXZUoPJcTWaUw369R706E.jpg',
        },
        {
          character: 'Flamethrower Soldier',
          credit_id: '5ec64d016c8492001f293ed6',
          order: 615,
          adult: false,
          gender: 2,
          id: 1396312,
          known_for_department: 'Acting',
          name: 'Dave MacDonald',
          original_name: 'Dave MacDonald',
          popularity: 0.84,
          profile_path: '/xqLpO30JWCyKkCQfuIBxIVSslpp.jpg',
        },
        {
          character: 'Claudia Henderson',
          credit_id: '5d25787669d2801be0036fc0',
          order: 643,
          adult: false,
          gender: 1,
          id: 205808,
          known_for_department: 'Acting',
          name: 'Catherine Curtin',
          original_name: 'Catherine Curtin',
          popularity: 5.288,
          profile_path: '/giB5pkibdukMBHAE0yLGs1JsPOH.jpg',
        },
        {
          character: 'Terry Ives',
          credit_id: '5d2578c937b3a94927529915',
          order: 691,
          adult: false,
          gender: 1,
          id: 1033252,
          known_for_department: 'Acting',
          name: 'Aimee Mullins',
          original_name: 'Aimee Mullins',
          popularity: 2.098,
          profile_path: '/A4H8dBREovAels6YFAw8wrprE8R.jpg',
        },
        {
          character: 'Ted Wheeler',
          credit_id: '5d267e6774645700126c239a',
          order: 697,
          adult: false,
          gender: 2,
          id: 141762,
          known_for_department: 'Acting',
          name: 'Joe Chrest',
          original_name: 'Joe Chrest',
          popularity: 3.424,
          profile_path: '/ox45oYzfnI9mxDYNeP01ZTRWGXC.jpg',
        },
        {
          character: 'Holly Wheeler',
          credit_id: '59fca91cc3a3681adf02ccbd',
          order: 747,
          adult: false,
          gender: 1,
          id: 1916843,
          known_for_department: 'Acting',
          name: 'Tinsley Price',
          original_name: 'Tinsley Price',
          popularity: 1.063,
          profile_path: '/y76Z7ewNyvPOvPudCNrHSFIuTth.jpg',
        },
      ],
    },
    {
      air_date: '2017-10-27',
      episode_number: 5,
      id: 1250987,
      name: 'Chapter Five: Dig Dug',
      overview:
        'Nancy and Jonathan swap conspiracy theories with a new ally as Eleven searches for someone from her past. “Bob the Brain” tackles a difficult problem.',
      production_code: '',
      runtime: 58,
      season_number: 2,
      show_id: 66732,
      still_path: '/westZSpDwRPjxG2eBWIT7utDcnL.jpg',
      vote_average: 8.2,
      vote_count: 119,
      crew: [
        {
          job: 'Writer',
          department: 'Writing',
          credit_id: '57b202d092514147840030b7',
          adult: false,
          gender: 0,
          id: 1666688,
          known_for_department: 'Writing',
          name: 'Jessie Nickson-Lopez',
          original_name: 'Jessie Nickson-Lopez',
          popularity: 1.746,
          profile_path: null,
        },
        {
          job: 'Director',
          department: 'Directing',
          credit_id: '59fbe8b592514113a6020823',
          adult: false,
          gender: 2,
          id: 7,
          known_for_department: 'Writing',
          name: 'Andrew Stanton',
          original_name: 'Andrew Stanton',
          popularity: 12.201,
          profile_path: '/gasNitCwepbqNcYBmDHpsCgZH0I.jpg',
        },
        {
          job: 'Director of Photography',
          department: 'Camera',
          credit_id: '60a81c446ee3d70029419e54',
          adult: false,
          gender: 2,
          id: 1485876,
          known_for_department: 'Camera',
          name: 'Tim Ives',
          original_name: 'Tim Ives',
          popularity: 0.6,
          profile_path: '/cgQkPbS2akrEZlawCi5DN0AkPqs.jpg',
        },
      ],
      guest_stars: [
        {
          character: 'Murray Bauman',
          credit_id: '5d257896e24e3a00112be743',
          order: 13,
          adult: false,
          gender: 2,
          id: 224197,
          known_for_department: 'Acting',
          name: 'Brett Gelman',
          original_name: 'Brett Gelman',
          popularity: 15.657,
          profile_path: '/ub2IuMWFNQGYghHTPq0lpmn2Ue0.jpg',
        },
        {
          character: 'Erica Sinclair',
          credit_id: '5d268d58dc86470012a56065',
          order: 14,
          adult: false,
          gender: 1,
          id: 2029806,
          known_for_department: 'Acting',
          name: 'Priah Ferguson',
          original_name: 'Priah Ferguson',
          popularity: 7.9,
          profile_path: '/wkVKPGdtqNQxr7zlKPpBFY63Rbv.jpg',
        },
        {
          character: 'Martin Brenner',
          credit_id: '5759b9c4c3a3683e7c003977',
          order: 15,
          adult: false,
          gender: 2,
          id: 8654,
          known_for_department: 'Acting',
          name: 'Matthew Modine',
          original_name: 'Matthew Modine',
          popularity: 15.171,
          profile_path: '/z974QEHL12qUvLyk6hlWGAmDgom.jpg',
        },
        {
          character: 'Ray',
          credit_id: '5d25799ae24e3a00132be88d',
          order: 531,
          adult: false,
          gender: 2,
          id: 3201,
          known_for_department: 'Acting',
          name: 'Pruitt Taylor Vince',
          original_name: 'Pruitt Taylor Vince',
          popularity: 14.2,
          profile_path: '/jqC1v8tF92QcmkQycnaLSuJiQfl.jpg',
        },
        {
          character: 'Becky Ives',
          credit_id: '5d2579b8a698cf0010ab33dd',
          order: 541,
          adult: false,
          gender: 1,
          id: 139150,
          known_for_department: 'Acting',
          name: 'Amy Seimetz',
          original_name: 'Amy Seimetz',
          popularity: 15.877,
          profile_path: '/9vnQvzBtkYza3hfkSOenUTNAXpH.jpg',
        },
        {
          character: 'Lab Technician',
          credit_id: '5d25895fe24e3a00132c0ea6',
          order: 569,
          adult: false,
          gender: 2,
          id: 1661269,
          known_for_department: 'Acting',
          name: 'Cory Chapman',
          original_name: 'Cory Chapman',
          popularity: 1.681,
          profile_path: '/clioIIwHWDs7C0BbkfE9gLtU08m.jpg',
        },
        {
          character: 'Keith',
          credit_id: '59fca77fc3a3681aa5032936',
          order: 579,
          adult: false,
          gender: 2,
          id: 979412,
          known_for_department: 'Acting',
          name: 'Matthew Cardarople',
          original_name: 'Matthew Cardarople',
          popularity: 6.458,
          profile_path: '/xhKO4iMPnwQS1GeDiY8vOyLFa8x.jpg',
        },
        {
          character: 'Claudia Henderson',
          credit_id: '5d25787669d2801be0036fc0',
          order: 643,
          adult: false,
          gender: 1,
          id: 205808,
          known_for_department: 'Acting',
          name: 'Catherine Curtin',
          original_name: 'Catherine Curtin',
          popularity: 5.288,
          profile_path: '/giB5pkibdukMBHAE0yLGs1JsPOH.jpg',
        },
        {
          character: 'Sue Sinclair',
          credit_id: '5b1f12950e0a264f9b010eba',
          order: 690,
          adult: false,
          gender: 1,
          id: 1377994,
          known_for_department: 'Acting',
          name: 'Karen Ceesay',
          original_name: 'Karen Ceesay',
          popularity: 2.345,
          profile_path: '/j7EKFC2RZa0gBMcJJTRhhydONEX.jpg',
        },
        {
          character: 'Terry Ives',
          credit_id: '5d2578c937b3a94927529915',
          order: 691,
          adult: false,
          gender: 1,
          id: 1033252,
          known_for_department: 'Acting',
          name: 'Aimee Mullins',
          original_name: 'Aimee Mullins',
          popularity: 2.098,
          profile_path: '/A4H8dBREovAels6YFAw8wrprE8R.jpg',
        },
        {
          character: 'Charles Sinclair',
          credit_id: '5d25897269d28024d0045105',
          order: 692,
          adult: false,
          gender: 2,
          id: 181521,
          known_for_department: 'Acting',
          name: 'Arnell Powell',
          original_name: 'Arnell Powell',
          popularity: 2.304,
          profile_path: '/m7Zl9av9H9CX76AxPyaYhHYIJWi.jpg',
        },
        {
          character: 'Ted Wheeler',
          credit_id: '5d267e6774645700126c239a',
          order: 697,
          adult: false,
          gender: 2,
          id: 141762,
          known_for_department: 'Acting',
          name: 'Joe Chrest',
          original_name: 'Joe Chrest',
          popularity: 3.424,
          profile_path: '/ox45oYzfnI9mxDYNeP01ZTRWGXC.jpg',
        },
      ],
    },
    {
      air_date: '2017-10-27',
      episode_number: 6,
      id: 1250988,
      name: 'Chapter Six: The Spy',
      overview:
        "Will's connection to a shadowy evil grows stronger, but no one's quite sure how to stop it. Elsewhere, Dustin and Steve forge an unlikely bond.",
      production_code: '',
      runtime: 52,
      season_number: 2,
      show_id: 66732,
      still_path: '/d90nCiTEACFEUd3fcX8DrLBi5DL.jpg',
      vote_average: 8.5,
      vote_count: 115,
      crew: [
        {
          job: 'Writer',
          department: 'Writing',
          credit_id: '59fcaa1d925141138b031070',
          adult: false,
          gender: 1,
          id: 1916848,
          known_for_department: 'Writing',
          name: 'Kate Trefry',
          original_name: 'Kate Trefry',
          popularity: 1.936,
          profile_path: '/RYoRQPYeGhSQP6y0X5x6LG8THM.jpg',
        },
        {
          job: 'Director',
          department: 'Directing',
          credit_id: '59fbe8b592514113a6020823',
          adult: false,
          gender: 2,
          id: 7,
          known_for_department: 'Writing',
          name: 'Andrew Stanton',
          original_name: 'Andrew Stanton',
          popularity: 12.201,
          profile_path: '/gasNitCwepbqNcYBmDHpsCgZH0I.jpg',
        },
        {
          job: 'Director of Photography',
          department: 'Camera',
          credit_id: '60a81c446ee3d70029419e54',
          adult: false,
          gender: 2,
          id: 1485876,
          known_for_department: 'Camera',
          name: 'Tim Ives',
          original_name: 'Tim Ives',
          popularity: 0.6,
          profile_path: '/cgQkPbS2akrEZlawCi5DN0AkPqs.jpg',
        },
      ],
      guest_stars: [
        {
          character: 'Murray Bauman',
          credit_id: '5d257896e24e3a00112be743',
          order: 13,
          adult: false,
          gender: 2,
          id: 224197,
          known_for_department: 'Acting',
          name: 'Brett Gelman',
          original_name: 'Brett Gelman',
          popularity: 15.657,
          profile_path: '/ub2IuMWFNQGYghHTPq0lpmn2Ue0.jpg',
        },
        {
          character: 'Erica Sinclair',
          credit_id: '5d268d58dc86470012a56065',
          order: 14,
          adult: false,
          gender: 1,
          id: 2029806,
          known_for_department: 'Acting',
          name: 'Priah Ferguson',
          original_name: 'Priah Ferguson',
          popularity: 7.9,
          profile_path: '/wkVKPGdtqNQxr7zlKPpBFY63Rbv.jpg',
        },
        {
          character: 'Nerdy Tech',
          credit_id: '59fca7f1c3a3681a8302d62d',
          order: 529,
          adult: false,
          gender: 0,
          id: 98191,
          known_for_department: 'Acting',
          name: 'Joe Davison',
          original_name: 'Joe Davison',
          popularity: 0.6,
          profile_path: null,
        },
        {
          character: 'Radar Tech',
          credit_id: '5d25791ca698cf59f5a76dc9',
          order: 530,
          adult: false,
          gender: 1,
          id: 1372293,
          known_for_department: 'Acting',
          name: 'Helen LeRoy',
          original_name: 'Helen LeRoy',
          popularity: 0.861,
          profile_path: '/mNy6ibVs7yHk4mwsL3daHL3nRL8.jpg',
        },
        {
          character: 'ER Doctor',
          credit_id: '5d25889269d2802c6e003033',
          order: 564,
          adult: false,
          gender: 1,
          id: 1217862,
          known_for_department: 'Acting',
          name: 'Mary Kraft',
          original_name: 'Mary Kraft',
          popularity: 1.886,
          profile_path: '/tBjDa5g4E0PllqIg3KHUGDKJGU7.jpg',
        },
        {
          character: 'Exam Room Nurse',
          credit_id: '5d2588a1e24e3a00102c123e',
          order: 565,
          adult: false,
          gender: 0,
          id: 1714699,
          known_for_department: 'Acting',
          name: 'Sheena Kharazmi',
          original_name: 'Sheena Kharazmi',
          popularity: 0.938,
          profile_path: null,
        },
        {
          character: 'Neurologist',
          credit_id: '5d2588d9a698cf3087a77789',
          order: 566,
          adult: false,
          gender: 2,
          id: 223022,
          known_for_department: 'Acting',
          name: "Brandon O'Dell",
          original_name: "Brandon O'Dell",
          popularity: 2.127,
          profile_path: '/mquFOZsnuUPpnrDRz6ie9FFnoXf.jpg',
        },
        {
          character: 'M.P. Guard #1',
          credit_id: '5d2587d369d28054b700c7ed',
          order: 567,
          adult: false,
          gender: 2,
          id: 1893361,
          known_for_department: 'Acting',
          name: 'Brian Brightman',
          original_name: 'Brian Brightman',
          popularity: 1.295,
          profile_path: '/pUZ7ShLvzMF2MpzcjcKor2bP7GL.jpg',
        },
        {
          character: 'M.P. Guard #2',
          credit_id: '5d2587ebe24e3a00122c0aa7',
          order: 568,
          adult: false,
          gender: 2,
          id: 1921106,
          known_for_department: 'Acting',
          name: 'Kristopher Charles',
          original_name: 'Kristopher Charles',
          popularity: 1.932,
          profile_path: '/Ldwt2UlS7IGNIFKeWELpJJr0S4.jpg',
        },
      ],
    },
    {
      air_date: '2017-10-27',
      episode_number: 7,
      id: 1250989,
      name: 'Chapter Seven: The Lost Sister',
      overview:
        'Psychic visions draw Eleven to a band of violent outcasts and an angry girl with a shadowy past.',
      production_code: '',
      runtime: 46,
      season_number: 2,
      show_id: 66732,
      still_path: '/kgOaaTbAutwAoA7tkVzYCfTjPXn.jpg',
      vote_average: 6.835,
      vote_count: 127,
      crew: [
        {
          job: 'Writer',
          department: 'Writing',
          credit_id: '57b203009251411a45000bb8',
          adult: false,
          gender: 2,
          id: 1301304,
          known_for_department: 'Writing',
          name: 'Justin Doble',
          original_name: 'Justin Doble',
          popularity: 0.6,
          profile_path: '/7bTwDKXb8BsvI5b1b4UeKQhBCCN.jpg',
        },
        {
          job: 'Director of Photography',
          department: 'Camera',
          credit_id: '60a81c446ee3d70029419e54',
          adult: false,
          gender: 2,
          id: 1485876,
          known_for_department: 'Camera',
          name: 'Tim Ives',
          original_name: 'Tim Ives',
          popularity: 0.6,
          profile_path: '/cgQkPbS2akrEZlawCi5DN0AkPqs.jpg',
        },
        {
          job: 'Director',
          department: 'Directing',
          credit_id: '60a81edf66e469002cf0c9ed',
          adult: false,
          gender: 1,
          id: 936974,
          known_for_department: 'Directing',
          name: 'Rebecca Thomas',
          original_name: 'Rebecca Thomas',
          popularity: 0.728,
          profile_path: '/oBEuF3C430rN277VbP64csrwRwC.jpg',
        },
      ],
      guest_stars: [
        {
          character: 'Martin Brenner',
          credit_id: '5759b9c4c3a3683e7c003977',
          order: 15,
          adult: false,
          gender: 2,
          id: 8654,
          known_for_department: 'Acting',
          name: 'Matthew Modine',
          original_name: 'Matthew Modine',
          popularity: 15.171,
          profile_path: '/z974QEHL12qUvLyk6hlWGAmDgom.jpg',
        },
        {
          character: 'Axel',
          credit_id: '5a008e90925141471d06aadd',
          order: 509,
          adult: false,
          gender: 2,
          id: 1170659,
          known_for_department: 'Acting',
          name: 'James Landry Hébert',
          original_name: 'James Landry Hébert',
          popularity: 6.811,
          profile_path: '/1WC4pv2BWJGNqqoo3CnCelXmGEE.jpg',
        },
        {
          character: 'Eight / Kali',
          credit_id: '5bdba8630e0a26333a002cb2',
          order: 525,
          adult: false,
          gender: 1,
          id: 1616155,
          known_for_department: 'Acting',
          name: 'Linnea Berthelsen',
          original_name: 'Linnea Berthelsen',
          popularity: 5.265,
          profile_path: '/u2UOvGHI4IoVfJmtP1I8F68VR50.jpg',
        },
        {
          character: 'Funshine',
          credit_id: '5d257959a698cf3087a752d7',
          order: 526,
          adult: false,
          gender: 2,
          id: 1448783,
          known_for_department: 'Acting',
          name: 'Kai Greene',
          original_name: 'Kai Greene',
          popularity: 1.706,
          profile_path: null,
        },
        {
          character: 'Dottie',
          credit_id: '5d257969e24e3a00122be860',
          order: 527,
          adult: false,
          gender: 1,
          id: 1107177,
          known_for_department: 'Acting',
          name: 'Anna Jacoby-Heron',
          original_name: 'Anna Jacoby-Heron',
          popularity: 2.049,
          profile_path: '/9CJdCKmlNWwQk8jXEi3GmknRYvd.jpg',
        },
        {
          character: 'Mick',
          credit_id: '5d25797937b3a94927529afd',
          order: 528,
          adult: false,
          gender: 1,
          id: 2358347,
          known_for_department: 'Acting',
          name: 'Gabrielle Maiden',
          original_name: 'Gabrielle Maiden',
          popularity: 0.6,
          profile_path: null,
        },
        {
          character: 'Ray',
          credit_id: '5d25799ae24e3a00132be88d',
          order: 531,
          adult: false,
          gender: 2,
          id: 3201,
          known_for_department: 'Acting',
          name: 'Pruitt Taylor Vince',
          original_name: 'Pruitt Taylor Vince',
          popularity: 14.2,
          profile_path: '/jqC1v8tF92QcmkQycnaLSuJiQfl.jpg',
        },
        {
          character: 'Becky Ives',
          credit_id: '5d2579b8a698cf0010ab33dd',
          order: 541,
          adult: false,
          gender: 1,
          id: 139150,
          known_for_department: 'Acting',
          name: 'Amy Seimetz',
          original_name: 'Amy Seimetz',
          popularity: 15.877,
          profile_path: '/9vnQvzBtkYza3hfkSOenUTNAXpH.jpg',
        },
        {
          character: 'Adams',
          credit_id: '59fca754925141137f030700',
          order: 560,
          adult: false,
          gender: 2,
          id: 1916834,
          known_for_department: 'Acting',
          name: 'Alan Boell',
          original_name: 'Alan Boell',
          popularity: 1.361,
          profile_path: '/vOgcUW3NqhI2IBvTaTBCJ8NX5pc.jpg',
        },
        {
          character: 'Elderly Woman',
          credit_id: '5d25882537b3a90011531750',
          order: 561,
          adult: false,
          gender: 1,
          id: 168703,
          known_for_department: 'Acting',
          name: 'Avis-Marie Barnes',
          original_name: 'Avis-Marie Barnes',
          popularity: 0.84,
          profile_path: '/fhlBsenWqADTTVOAlyo0FnKHzWE.jpg',
        },
        {
          character: 'Mentally Ill Man',
          credit_id: '5d25883fa698cf0fa7a856ee',
          order: 562,
          adult: false,
          gender: 0,
          id: 2253135,
          known_for_department: 'Acting',
          name: 'PJ McDonnell',
          original_name: 'PJ McDonnell',
          popularity: 0.6,
          profile_path: null,
        },
        {
          character: 'Gas Station Clerk',
          credit_id: '5d258865a698cf3087a776c0',
          order: 563,
          adult: false,
          gender: 2,
          id: 1156146,
          known_for_department: 'Acting',
          name: 'Keith Brooks',
          original_name: 'Keith Brooks',
          popularity: 1.623,
          profile_path: null,
        },
        {
          character: 'Terry Ives',
          credit_id: '5d2578c937b3a94927529915',
          order: 691,
          adult: false,
          gender: 1,
          id: 1033252,
          known_for_department: 'Acting',
          name: 'Aimee Mullins',
          original_name: 'Aimee Mullins',
          popularity: 2.098,
          profile_path: '/A4H8dBREovAels6YFAw8wrprE8R.jpg',
        },
      ],
    },
    {
      air_date: '2017-10-27',
      episode_number: 8,
      id: 1250990,
      name: 'Chapter Eight: The Mind Flayer',
      overview:
        'An unlikely hero steps forward when a deadly development puts the Hawkins Lab on lockdown, trapping Will and several others inside.',
      production_code: '',
      runtime: 48,
      season_number: 2,
      show_id: 66732,
      still_path: '/k3cEwGAWSWbkauYBHSdFnEdalkb.jpg',
      vote_average: 8.5,
      vote_count: 119,
      crew: [
        {
          job: 'Director',
          department: 'Directing',
          credit_id: '57b20164c3a36869e5000ba5',
          adult: false,
          gender: 2,
          id: 1179419,
          known_for_department: 'Writing',
          name: 'Matt Duffer',
          original_name: 'Matt Duffer',
          popularity: 3.732,
          profile_path: '/kXO5CnSxC0znMAICGxnPeuGP73U.jpg',
        },
        {
          job: 'Director',
          department: 'Directing',
          credit_id: '57b20174c3a3686a54000afa',
          adult: false,
          gender: 2,
          id: 1179422,
          known_for_department: 'Writing',
          name: 'Ross Duffer',
          original_name: 'Ross Duffer',
          popularity: 3.641,
          profile_path: '/kN1HdFViQkcJOQlNcvvFJIx9Uju.jpg',
        },
        {
          job: 'Writer',
          department: 'Writing',
          credit_id: '5789c497c3a36841e70009b9',
          adult: false,
          gender: 2,
          id: 1179422,
          known_for_department: 'Writing',
          name: 'Ross Duffer',
          original_name: 'Ross Duffer',
          popularity: 3.641,
          profile_path: '/kN1HdFViQkcJOQlNcvvFJIx9Uju.jpg',
        },
        {
          job: 'Writer',
          department: 'Writing',
          credit_id: '5789c46cc3a36841e700099e',
          adult: false,
          gender: 2,
          id: 1179419,
          known_for_department: 'Writing',
          name: 'Matt Duffer',
          original_name: 'Matt Duffer',
          popularity: 3.732,
          profile_path: '/kXO5CnSxC0znMAICGxnPeuGP73U.jpg',
        },
        {
          job: 'Director of Photography',
          department: 'Camera',
          credit_id: '60a81c446ee3d70029419e54',
          adult: false,
          gender: 2,
          id: 1485876,
          known_for_department: 'Camera',
          name: 'Tim Ives',
          original_name: 'Tim Ives',
          popularity: 0.6,
          profile_path: '/cgQkPbS2akrEZlawCi5DN0AkPqs.jpg',
        },
      ],
      guest_stars: [
        {
          character: 'Radar Tech',
          credit_id: '5d25791ca698cf59f5a76dc9',
          order: 530,
          adult: false,
          gender: 1,
          id: 1372293,
          known_for_department: 'Acting',
          name: 'Helen LeRoy',
          original_name: 'Helen LeRoy',
          popularity: 0.861,
          profile_path: '/mNy6ibVs7yHk4mwsL3daHL3nRL8.jpg',
        },
        {
          character: 'M.P. Guard #1',
          credit_id: '5d2587d369d28054b700c7ed',
          order: 567,
          adult: false,
          gender: 2,
          id: 1893361,
          known_for_department: 'Acting',
          name: 'Brian Brightman',
          original_name: 'Brian Brightman',
          popularity: 1.295,
          profile_path: '/pUZ7ShLvzMF2MpzcjcKor2bP7GL.jpg',
        },
        {
          character: 'M.P. Guard #2',
          credit_id: '5d2587ebe24e3a00122c0aa7',
          order: 568,
          adult: false,
          gender: 2,
          id: 1921106,
          known_for_department: 'Acting',
          name: 'Kristopher Charles',
          original_name: 'Kristopher Charles',
          popularity: 1.932,
          profile_path: '/Ldwt2UlS7IGNIFKeWELpJJr0S4.jpg',
        },
        {
          character: 'Neil Hargrove',
          credit_id: '5bdba985925141783c002b3e',
          order: 584,
          adult: false,
          gender: 2,
          id: 87927,
          known_for_department: 'Acting',
          name: 'Will Chase',
          original_name: 'Will Chase',
          popularity: 2.144,
          profile_path: '/2HqBRqcSKiG7Szq8mTjtNuAuYBR.jpg',
        },
        {
          character: 'Susan Hargrove',
          credit_id: '5bdba9afc3a3684038002d35',
          order: 748,
          adult: false,
          gender: 1,
          id: 565342,
          known_for_department: 'Acting',
          name: 'Jennifer L. Marshall',
          original_name: 'Jennifer L. Marshall',
          popularity: 1.833,
          profile_path: '/ixePOGabSZhJ8bfDSfrkSBglBFc.jpg',
        },
      ],
    },
    {
      air_date: '2017-10-27',
      episode_number: 9,
      id: 1250991,
      name: 'Chapter Nine: The Gate',
      overview:
        "Eleven makes plans to finish what she started while the survivors turn up the heat on the monstrous force that's holding Will hostage.",
      production_code: '',
      runtime: 62,
      season_number: 2,
      show_id: 66732,
      still_path: '/wqwAsocYrxl7MtHiY8ZAsIxrX5v.jpg',
      vote_average: 8.5,
      vote_count: 119,
      crew: [
        {
          job: 'Director',
          department: 'Directing',
          credit_id: '57b20164c3a36869e5000ba5',
          adult: false,
          gender: 2,
          id: 1179419,
          known_for_department: 'Writing',
          name: 'Matt Duffer',
          original_name: 'Matt Duffer',
          popularity: 3.732,
          profile_path: '/kXO5CnSxC0znMAICGxnPeuGP73U.jpg',
        },
        {
          job: 'Director',
          department: 'Directing',
          credit_id: '57b20174c3a3686a54000afa',
          adult: false,
          gender: 2,
          id: 1179422,
          known_for_department: 'Writing',
          name: 'Ross Duffer',
          original_name: 'Ross Duffer',
          popularity: 3.641,
          profile_path: '/kN1HdFViQkcJOQlNcvvFJIx9Uju.jpg',
        },
        {
          job: 'Writer',
          department: 'Writing',
          credit_id: '5789c497c3a36841e70009b9',
          adult: false,
          gender: 2,
          id: 1179422,
          known_for_department: 'Writing',
          name: 'Ross Duffer',
          original_name: 'Ross Duffer',
          popularity: 3.641,
          profile_path: '/kN1HdFViQkcJOQlNcvvFJIx9Uju.jpg',
        },
        {
          job: 'Writer',
          department: 'Writing',
          credit_id: '5789c46cc3a36841e700099e',
          adult: false,
          gender: 2,
          id: 1179419,
          known_for_department: 'Writing',
          name: 'Matt Duffer',
          original_name: 'Matt Duffer',
          popularity: 3.732,
          profile_path: '/kXO5CnSxC0znMAICGxnPeuGP73U.jpg',
        },
        {
          job: 'Director of Photography',
          department: 'Camera',
          credit_id: '60a81c446ee3d70029419e54',
          adult: false,
          gender: 2,
          id: 1485876,
          known_for_department: 'Camera',
          name: 'Tim Ives',
          original_name: 'Tim Ives',
          popularity: 0.6,
          profile_path: '/cgQkPbS2akrEZlawCi5DN0AkPqs.jpg',
        },
      ],
      guest_stars: [
        {
          character: 'Murray Bauman',
          credit_id: '5d257896e24e3a00112be743',
          order: 13,
          adult: false,
          gender: 2,
          id: 224197,
          known_for_department: 'Acting',
          name: 'Brett Gelman',
          original_name: 'Brett Gelman',
          popularity: 15.657,
          profile_path: '/ub2IuMWFNQGYghHTPq0lpmn2Ue0.jpg',
        },
        {
          character: 'Erica Sinclair',
          credit_id: '5d268d58dc86470012a56065',
          order: 14,
          adult: false,
          gender: 1,
          id: 2029806,
          known_for_department: 'Acting',
          name: 'Priah Ferguson',
          original_name: 'Priah Ferguson',
          popularity: 7.9,
          profile_path: '/wkVKPGdtqNQxr7zlKPpBFY63Rbv.jpg',
        },
        {
          character: 'Martin Brenner',
          credit_id: '5759b9c4c3a3683e7c003977',
          order: 15,
          adult: false,
          gender: 2,
          id: 8654,
          known_for_department: 'Acting',
          name: 'Matthew Modine',
          original_name: 'Matthew Modine',
          popularity: 15.171,
          profile_path: '/z974QEHL12qUvLyk6hlWGAmDgom.jpg',
        },
        {
          character: 'Eight / Kali',
          credit_id: '5bdba8630e0a26333a002cb2',
          order: 525,
          adult: false,
          gender: 1,
          id: 1616155,
          known_for_department: 'Acting',
          name: 'Linnea Berthelsen',
          original_name: 'Linnea Berthelsen',
          popularity: 5.265,
          profile_path: '/u2UOvGHI4IoVfJmtP1I8F68VR50.jpg',
        },
        {
          character: 'Marsha Holland',
          credit_id: '59fca73bc3a3681acd02f597',
          order: 535,
          adult: false,
          gender: 1,
          id: 995451,
          known_for_department: 'Acting',
          name: 'Cynthia Barrett',
          original_name: 'Cynthia Barrett',
          popularity: 1.837,
          profile_path: '/tWd0Yr3uIkHxnJevJ5gFtsKp0LU.jpg',
        },
        {
          character: 'Scott Clarke',
          credit_id: '5d2578ada698cf0010ab31cb',
          order: 605,
          adult: false,
          gender: 2,
          id: 1381393,
          known_for_department: 'Acting',
          name: 'Randy Havens',
          original_name: 'Randy Havens',
          popularity: 6.293,
          profile_path: '/7Lh5eGcXZUoPJcTWaUw369R706E.jpg',
        },
        {
          character: 'Middle School Student (uncredited)',
          credit_id: '5eae892ecdbaff0021b17301',
          order: 614,
          adult: false,
          gender: 2,
          id: 2623723,
          known_for_department: 'Acting',
          name: 'Gage Lawson',
          original_name: 'Gage Lawson',
          popularity: 1.4,
          profile_path: '/gYowFnKxGAEaPfNvHZMK2pVLEEP.jpg',
        },
        {
          character: 'Stacey',
          credit_id: '5f024da48ec4ab00334017c2',
          order: 616,
          adult: false,
          gender: 1,
          id: 2134661,
          known_for_department: 'Acting',
          name: 'Sydney Bullock',
          original_name: 'Sydney Bullock',
          popularity: 2.315,
          profile_path: '/kH01VhaMPf4czUPl1XZ0TrNMu4O.jpg',
        },
        {
          character: 'Claudia Henderson',
          credit_id: '5d25787669d2801be0036fc0',
          order: 643,
          adult: false,
          gender: 1,
          id: 205808,
          known_for_department: 'Acting',
          name: 'Catherine Curtin',
          original_name: 'Catherine Curtin',
          popularity: 5.288,
          profile_path: '/giB5pkibdukMBHAE0yLGs1JsPOH.jpg',
        },
        {
          character: 'Terry Ives',
          credit_id: '5d2578c937b3a94927529915',
          order: 691,
          adult: false,
          gender: 1,
          id: 1033252,
          known_for_department: 'Acting',
          name: 'Aimee Mullins',
          original_name: 'Aimee Mullins',
          popularity: 2.098,
          profile_path: '/A4H8dBREovAels6YFAw8wrprE8R.jpg',
        },
        {
          character: 'Ted Wheeler',
          credit_id: '5d267e6774645700126c239a',
          order: 697,
          adult: false,
          gender: 2,
          id: 141762,
          known_for_department: 'Acting',
          name: 'Joe Chrest',
          original_name: 'Joe Chrest',
          popularity: 3.424,
          profile_path: '/ox45oYzfnI9mxDYNeP01ZTRWGXC.jpg',
        },
        {
          character: 'Susan Hargrove',
          credit_id: '5bdba9afc3a3684038002d35',
          order: 748,
          adult: false,
          gender: 1,
          id: 565342,
          known_for_department: 'Acting',
          name: 'Jennifer L. Marshall',
          original_name: 'Jennifer L. Marshall',
          popularity: 1.833,
          profile_path: '/ixePOGabSZhJ8bfDSfrkSBglBFc.jpg',
        },
      ],
    },
  ],
  name: 'Stranger Things 2',
  overview:
    "It's been nearly a year since Will's strange disappearance. But life's hardly back to normal in Hawkins. Not even close.",
  id: 83248,
  poster_path: '/lXS60geme1LlEob5Wgvj3KilClA.jpg',
  season_number: 2,
};
