
@hostName = https://api.themoviedb.org/3/
@apiKey = 29e9c21417a5cdd0f56b401142fdba10
@tvId = 66732


### TV details
GET {{hostName}}/tv/{{tvId}}?api_key={{apiKey}}

### Credits
GET {{hostName}}/tv/{{tvId}}/credits?api_key={{apiKey}}

### Content Ratings
GET {{hostName}}/tv/{{tvId}}/content_ratings?api_key={{apiKey}}


### TV Seasons - Get details
@season_number = 2
GET {{hostName}}/tv/{{tvId}}/season/{{season_number}}?api_key={{apiKey}}